package com.vlad.ducknetview.data

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.vlad.ducknetview.data.db.DuckDatabase
import com.vlad.ducknetview.data.db.EventEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [33])
class EventDaoTest {

    private lateinit var db: DuckDatabase

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            DuckDatabase::class.java,
        ).allowMainThreadQueries().build()
    }

    @After
    fun tearDown() = db.close()

    private fun event(at: Long, level: String = "INFO", subject: String = "s") = EventEntity(
        at = at,
        level = level,
        kind = "service_up",
        subject = subject,
        detail = "",
    )

    @Test
    fun `recent returns newest first`() = runTest {
        db.events().insert(listOf(event(100, subject = "a"), event(300, subject = "c"), event(200, subject = "b")))
        val rows = db.events().recent(10).first()
        assertEquals(listOf("c", "b", "a"), rows.map { it.subject })
    }

    @Test
    fun `recent honours its limit`() = runTest {
        db.events().insert((1L..20L).map { event(it * 10, subject = "e$it") })
        val rows = db.events().recent(5).first()
        assertEquals(5, rows.size)
        assertEquals(listOf("e20", "e19", "e18", "e17", "e16"), rows.map { it.subject })
    }

    @Test
    fun `events sharing a millisecond keep a deterministic newest-first order`() = runTest {
        db.events().insert(listOf(event(500, subject = "first"), event(500, subject = "second")))
        val rows = db.events().recent(10).first()
        assertEquals(listOf("second", "first"), rows.map { it.subject })
    }

    @Test
    fun `prune drops only rows older than the cutoff`() = runTest {
        db.events().insert(listOf(event(100), event(200), event(300)))
        db.events().pruneOlderThan(200)
        assertEquals(listOf(300L, 200L), db.events().recent(10).first().map { it.at })
    }

    @Test
    fun `prune with a cutoff below everything keeps every row`() = runTest {
        db.events().insert(listOf(event(100), event(200)))
        db.events().pruneOlderThan(1)
        assertEquals(2, db.events().count())
    }

    @Test
    fun `clear empties the table`() = runTest {
        db.events().insert(listOf(event(1), event(2)))
        db.events().clear()
        assertEquals(0, db.events().count())
        assertEquals(emptyList<EventEntity>(), db.events().recent(10).first())
    }

    @Test
    fun `countSince counts only the requested levels strictly after the timestamp`() = runTest {
        db.events().insert(
            listOf(
                event(100, level = "INFO"),
                event(200, level = "WARN"),
                event(300, level = "ALERT"),
                event(400, level = "INFO"),
            )
        )
        val levels = listOf("WARN", "ALERT")
        assertEquals(2, db.events().countSince(0, levels).first())
        assertEquals(1, db.events().countSince(200, levels).first())
        assertEquals(0, db.events().countSince(300, levels).first())
    }

    @Test
    fun `allForExport returns every row oldest first`() = runTest {
        db.events().insert(listOf(event(300, subject = "c"), event(100, subject = "a"), event(200, subject = "b")))
        assertEquals(listOf("a", "b", "c"), db.events().allForExport().map { it.subject })
    }

    @Test
    fun `insert assigns increasing autogenerated ids`() = runTest {
        db.events().insert(listOf(event(1), event(2)))
        val ids = db.events().allForExport().map { it.id }
        assertEquals(listOf(1L, 2L), ids)
    }
}
